### ISSUE TITLE
doesnt stop me from doing this 

### ISSUE THREAD

**Issue by givemhell** [superarts/d2r-loot-filter#3]
lmfao you didnt want to discuss it in the first place hence why you shutdown the convo before it could even start 
its w/e dude upload my stuff anywhere and il reach out to the mods and have it removed

**Comment by givemhell** [comment]
you also still need to delete my mod from your other branch opeing a ticket with github now about it

**Comment by superarts** [comment]
Wait a sec I thought you modified Blizzard client configuration file and you are claiming the copyright of it? 

Anyway I updated my Reddit post and upvoted your reply. I hope more people will see your reply and agree with you so that they will decide to use your mod.

**Comment by superarts** [comment]
Report this user if you are under cyber attack! This is what I sent to github support:

____________

This user attacked me so I just blocked him. However, he started performing cyber attack by adding my email to some random mailing lists to spam me. These are some examples:

![image.png](https://github.zendesk.com/attachments/token/dnA5WzmreZBFGUHrGbmAEDzxN/?name=image.png)

I understand that I cannot fully establish an evidence chain to tie this particular user to this attack, as he probably just adds my email to some public mail lists, possibly by scripting it automatically. However, I report this issue because if there are more victims related with this user, you can take actions accordingly.

Thanks!
